version: '3.8'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: ope079/python-frontend:latest
    environment:
      DATABASE_URI: ${DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
    ports:
    - target: 5000
      published: 5000
  backend1:
    container_name: backend1
    build: ./backend1
    image: ope079/python-backend1:latest
    
  backend2:
    container_name: backend2
    build: ./backend2
    image: ope079/python-backend2:latest
    
  backend3:
    container_name: backend3
    build: ./backend3
    image: ope079/python-frontend:latest

  nginx:
    container_name: nginx
    image: nginx:latest

  
