version: '3.8'
services:
  frontend:
    container_name: sfia-task-2_frontend
    build: ./frontend
    image: ope079/python-frontend:latest
    environment:
      DATABASE_URI: ${DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  backend1:
    container_name: sfia-task-2_backend1
    build: ./backend1
    image: ope079/python-backend1:latest
    ports:
    - target: 5001
      published: 5001  
  backend2:
    container_name: sfia-task-2_backend2
    build: ./backend2
    image: ope079/python-backend2:latest
    ports:
    - target: 5002
      published: 5002    
  backend3:
    container_name: sfia-task-2_backend3
    build: ./backend3
    image: ope079/python-backend3:latest
    ports:
    - target: 5003
      published: 5003
