version: '3.8'
services:
  frontend:
    container_name: sfia-task-2_frontend
    build: ./frontend
    image: ope079/python-frontend:latest
    environment:
      DATABASE_URI: ${DATABASE_URI}
      SECRET_KEY: ${SECRET_KEY}
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  backend1:
    container_name: sfia-task-2_backend1
    build: ./backend1
    image: ope079/python-backend1:latest
   
  backend2:
    container_name: sfia-task-2_backend2
    build: ./backend2
    image: ope079/python-backend2:latest
    
  backend3:
    container_name: sfia-task-2_backend3
    build: ./backend3
    image: ope079/python-frontend:latest
  
#  nginx:
 #   container_name: nginx:alpine 
  #  build: ./nginx
   # image: ope079/nginx:alpine
    #ports:
    #- "80:80"
  #  depends_on:
   # - frontend
  #  - backend1
  #  - backend2
  #  - backend3
