pipeline{
    agent any
    environment{
        version = "v2"
        DATABASE_URI = credentials("DATABASE_URI")
        CHROMEDRIVER_PATH = "/home/jenkins/chromedriver"
        AUTHOR = "ope079"
        rollback = 'false'
        replicas = 5
        SECRET_KEY = credentials("SECRET_KEY")
    }
    stages{

        stage("Test"){
            steps{
                script{
                    if(env.rollback == 'false'){
                        sh "bash jenkins/test.sh"
                    }
                }
            }
        }
        
        stage("Build and Push Images"){
            steps{
                    script{
                    if (env.rollback == 'false'){
                        sh "bash jenkins/build_images.sh"
                    }   
                }
            }
        }
        stage("Configuration Management"){
            steps{
                sh "cd ansible && /home/jenkins/.local/bin/ansible-playbook -i inventory playbook.yaml"
            }
        }
        stage("Deploy"){
            steps{
                sh "bash jenkins/deploy_stack.sh"
            }
        }
    }
    post {
        always {
            junit '**/junit.xml'
            cobertura coberturaReportFile: '**/coverage.xml', failNoReports: false, failUnstable: false, onlyStable:false
        }
    }
    
}