- name: "Uninstall NginX"
  apt:
    name: nginx
    state: absent

- name: "Stop Nginx Services"
  service:
    name: nginx
    state: stopped


- name: Install NGINX
  apt:
    name: nginx
    state: latest
    update_cache: true

- name: Start NGINX Service
  service:
    name: nginx
    state: started