---
- name: initialize docker swarm
  become: true
  hosts: managers
  roles:
    - nginx
    - docker
    - docker-swarm-init
    
- name: add workers to swarm
  become: true
  hosts: workers
  roles:
    - nginx
    - docker
    - docker-swarm-workers
    
- name: start nginx
  become: true
  hosts: nginx
  roles:
    - nginx
    - docker
    - nginx-configure